#!/usr/bin/env python3
"""
Final verification that Phase 4 schema issues are resolved and models can be trained.
"""

import pandas as pd
import numpy as np
import os

def test_schema_transformation_complete():
    """Test complete schema transformation pipeline."""
    print("=== Final Schema Transformation Test ===")
    
    # Step 1: Simulate data exactly as produced by data_streaming/data_generator.py
    print("\n1. Simulating data_streaming output...")
    
    # Transaction data as generated by data_generator.py
    streaming_transactions = pd.DataFrame({
        'transactionId': [f'txn_{i}' for i in range(20)],
        'userId': [f'user_{i%5}' for i in range(20)],
        'productId': [f'prod_{i%3}' for i in range(20)],
        'quantity': np.random.randint(1, 5, 20),
        'totalPrice': np.random.uniform(50, 500, 20),
        'transactionDate': pd.date_range('2024-01-01', periods=20, freq='D'),
        'status': ['completed'] * 20,
        'paymentMethod': ['credit_card'] * 20
    })
    
    # Product data as generated by data_generator.py
    streaming_products = pd.DataFrame({
        'productId': [f'prod_{i}' for i in range(3)],
        'name': [f'Product {i}' for i in range(3)],
        'category': ['Electronics', 'Books', 'Apparel'],
        'price': [100.0, 50.0, 75.0],
        'stock': [100, 50, 75]
    })
    
    # User data as generated by data_generator.py
    streaming_users = pd.DataFrame({
        'userId': [f'user_{i}' for i in range(5)],
        'username': [f'user{i}' for i in range(5)],
        'email': [f'user{i}@example.com' for i in range(5)]
    })
    
    print(f"Streaming transactions columns: {list(streaming_transactions.columns)}")
    print(f"Streaming products columns: {list(streaming_products.columns)}")
    print(f"Streaming users columns: {list(streaming_users.columns)}")
    
    # Step 2: Apply ModelManager schema transformation
    print("\n2. Applying ModelManager schema transformation...")
    
    # Transform transactions (as done in ModelManager)
    transformed_transactions = streaming_transactions.rename(columns={
        'productId': 'product_id',
        'userId': 'user_id',
        'transactionId': 'transaction_id',
        'transactionDate': 'timestamp',
        'totalPrice': 'amount',
        'totalAmount': 'amount'  # Keep both mappings for compatibility
    })
    
    # Transform products
    transformed_products = streaming_products.rename(columns={
        'productId': 'product_id'
    })
    
    # Transform users
    transformed_users = streaming_users.rename(columns={
        'userId': 'user_id'
    })
    
    print(f"Transformed transactions columns: {list(transformed_transactions.columns)}")
    print(f"Transformed products columns: {list(transformed_products.columns)}")
    print(f"Transformed users columns: {list(transformed_users.columns)}")
    
    # Step 3: Verify all Phase 4 model requirements are met
    print("\n3. Verifying Phase 4 model requirements...")
    
    # DynamicPricingModel requirements
    pricing_required = ['product_id', 'user_id', 'amount', 'quantity', 'category', 'timestamp']
    
    # Merge transactions with products to get category for pricing model
    pricing_data = transformed_transactions.merge(
        transformed_products[['product_id', 'category', 'price']], 
        on='product_id', 
        how='left'
    )
    
    pricing_missing = [col for col in pricing_required if col not in pricing_data.columns]
    print(f"DynamicPricingModel - Required: {pricing_required}")
    print(f"DynamicPricingModel - Missing: {pricing_missing if pricing_missing else 'None ✓'}")
    
    # ChurnPredictionModel requirements
    churn_required = ['user_id', 'product_id', 'transaction_id', 'amount', 'timestamp']
    churn_missing = [col for col in churn_required if col not in transformed_transactions.columns]
    print(f"ChurnPredictionModel - Required: {churn_required}")
    print(f"ChurnPredictionModel - Missing: {churn_missing if churn_missing else 'None ✓'}")
    
    # KnowledgeGraph requirements
    kg_required_transactions = ['user_id', 'product_id', 'transaction_id', 'amount']
    kg_required_products = ['product_id', 'category']
    kg_required_users = ['user_id']
    
    kg_tx_missing = [col for col in kg_required_transactions if col not in transformed_transactions.columns]
    kg_prod_missing = [col for col in kg_required_products if col not in transformed_products.columns]
    kg_user_missing = [col for col in kg_required_users if col not in transformed_users.columns]
    
    print(f"KnowledgeGraph - Transactions required: {kg_required_transactions}")
    print(f"KnowledgeGraph - Transactions missing: {kg_tx_missing if kg_tx_missing else 'None ✓'}")
    print(f"KnowledgeGraph - Products required: {kg_required_products}")
    print(f"KnowledgeGraph - Products missing: {kg_prod_missing if kg_prod_missing else 'None ✓'}")
    print(f"KnowledgeGraph - Users required: {kg_required_users}")
    print(f"KnowledgeGraph - Users missing: {kg_user_missing if kg_user_missing else 'None ✓'}")
    
    # Step 4: Verify data types
    print("\n4. Verifying data types...")
    
    # Ensure timestamp is datetime
    transformed_transactions['timestamp'] = pd.to_datetime(transformed_transactions['timestamp'])
    print(f"✓ Timestamp converted to datetime: {transformed_transactions['timestamp'].dtype}")
    
    # Ensure numeric columns are numeric
    transformed_transactions['amount'] = pd.to_numeric(transformed_transactions['amount'])
    transformed_transactions['quantity'] = pd.to_numeric(transformed_transactions['quantity'])
    print(f"✓ Amount is numeric: {transformed_transactions['amount'].dtype}")
    print(f"✓ Quantity is numeric: {transformed_transactions['quantity'].dtype}")
    
    # Step 5: Final assessment
    print("\n=== Final Assessment ===")
    
    all_requirements_met = (
        not pricing_missing and 
        not churn_missing and 
        not kg_tx_missing and 
        not kg_prod_missing and 
        not kg_user_missing
    )
    
    if all_requirements_met:
        print("✅ ALL PHASE 4 MODEL REQUIREMENTS ARE MET!")
        print("✅ Schema transformation from data_streaming to Phase 4 models is COMPLETE")
        print("✅ Phase 4 models should now train successfully with real data")
        
        # Show sample of final data
        print("\nSample of final transformed data:")
        print(pricing_data[['product_id', 'user_id', 'amount', 'quantity', 'category', 'timestamp']].head())
        
        return True
    else:
        print("❌ Some requirements are still missing")
        return False

if __name__ == "__main__":
    success = test_schema_transformation_complete()
    
    if success:
        print("\n🎉 Schema compatibility verification PASSED!")
        print("🎉 Phase 4 models are ready for training with data_streaming pipeline!")
    else:
        print("\n❌ Schema compatibility verification FAILED!")
        print("❌ Additional fixes needed before Phase 4 models can train successfully")
